// Generated by `cargo xtask gen` from project.toml. Do not edit.

/// Product name shown to people.
pub const PRODUCT_NAME: &str = "WebeSign";

/// Lowercase ASCII name for binaries, folders and files.
pub const SLUG: &str = "websign";

/// One-line English description.
pub const TAGLINE: &str = "Sign with your digital certificate on any website or app.";

/// Source repository URL.
pub const REPOSITORY: &str = "https://github.com/diagnos-tech/web-esign";

/// Website (download, privacy, `/activate`, `/test`).
pub const HOMEPAGE: &str = "https://diagnos-tech.github.io/web-esign/";

/// Native messaging host name (`[a-z0-9_.]` only).
pub const NATIVE_HOST: &str = "dev.websign.host";

/// URL scheme the app registers, without the colon.
pub const URL_SCHEME: &str = "websign";

/// macOS bundle identifier.
pub const MACOS_BUNDLE_ID: &str = "dev.websign.app";

/// macOS app group shared with the Safari extension.
pub const MACOS_APP_GROUP: &str = "TEAMID.dev.websign";

/// Firefox (Gecko) extension ID.
pub const FIREFOX_ID: &str = "websign@dev.websign";

/// Chromium extension ID of the development build (pinned by its public key).
pub const EXTENSION_DEV_ID: &str = "nhnkdpljdgjflbflkhnkmfmcmodboeii";

/// Chrome Web Store ID; empty until published.
pub const CHROME_WEB_STORE_ID: &str = "";

/// Edge Add-ons ID; empty until published.
pub const EDGE_ADDONS_ID: &str = "";

/// Oldest app version the extension accepts.
pub const MIN_APP_VERSION: &str = "0.1.0";
