//! `project.toml` → `crates/websign-project/src/generated.rs`.
//!
//! The constants are committed rather than produced by a build script: a
//! build script would read `../../project.toml`, which is outside the crate
//! and so missing from the package crates.io builds.

use std::path::Path;

use crate::fsutil::read_text;
use crate::plan::Plan;

const OUTPUT: &str = "crates/websign-project/src/generated.rs";

/// rustfmt's line width; a longer `pub const` wraps after `=` like rustfmt
/// would, so `cargo fmt --check` accepts the file as generated.
const LINE_WIDTH: usize = 100;

/// `(constant, table, key, doc comment)` for every exported string.
const CONSTANTS: [(&str, &str, &str, &str); 15] = [
    (
        "PRODUCT_NAME",
        "product",
        "name",
        "Product name shown to people.",
    ),
    (
        "SLUG",
        "product",
        "slug",
        "Lowercase ASCII name for binaries, folders and files.",
    ),
    (
        "TAGLINE",
        "product",
        "tagline",
        "One-line English description.",
    ),
    (
        "REPOSITORY",
        "product",
        "repository",
        "Source repository URL.",
    ),
    (
        "HOMEPAGE",
        "product",
        "homepage",
        "Website (download, privacy, `/activate`, `/test`).",
    ),
    (
        "NATIVE_HOST",
        "ids",
        "native_host",
        "Native messaging host name (`[a-z0-9_.]` only).",
    ),
    (
        "URL_SCHEME",
        "ids",
        "url_scheme",
        "URL scheme the app registers, without the colon.",
    ),
    (
        "MACOS_BUNDLE_ID",
        "ids",
        "macos_bundle_id",
        "macOS bundle identifier.",
    ),
    (
        "MACOS_APP_GROUP",
        "ids",
        "macos_app_group",
        "macOS app group shared with the Safari extension.",
    ),
    (
        "SAFARI_EXTENSION_BUNDLE_ID",
        "ids",
        "safari_extension_bundle_id",
        "Bundle identifier of the Safari app extension inside the macOS app.",
    ),
    (
        "FIREFOX_ID",
        "extension",
        "firefox_id",
        "Firefox (Gecko) extension ID.",
    ),
    (
        "EXTENSION_DEV_ID",
        "extension",
        "dev_id",
        "Chromium extension ID of the development build (pinned by its public key).",
    ),
    (
        "CHROME_WEB_STORE_ID",
        "extension",
        "chrome_web_store_id",
        "Chrome Web Store ID; empty until published.",
    ),
    (
        "EDGE_ADDONS_ID",
        "extension",
        "edge_addons_id",
        "Edge Add-ons ID; empty until published.",
    ),
    (
        "MIN_APP_VERSION",
        "extension",
        "min_app_version",
        "Oldest app version the extension accepts.",
    ),
];

pub fn plan(root: &Path) -> Result<Plan, String> {
    let table: toml::Table = read_text(&root.join("project.toml"))?
        .parse()
        .map_err(|e| format!("project.toml is not valid TOML: {e}"))?;
    let mut plan = Plan::default();
    plan.add(OUTPUT, render(&table)?);
    Ok(plan)
}

fn render(table: &toml::Table) -> Result<String, String> {
    let mut out =
        String::from("// Generated by `cargo xtask gen` from project.toml. Do not edit.\n");
    for (name, section, key, doc) in CONSTANTS {
        let value = table
            .get(section)
            .and_then(|s| s.get(key))
            .and_then(toml::Value::as_str)
            .ok_or_else(|| format!("project.toml: missing string `[{section}] {key}`"))?;
        let line = format!("pub const {name}: &str = {value:?};");
        out.push_str(&format!("\n/// {doc}\n"));
        if line.len() > LINE_WIDTH {
            out.push_str(&format!("pub const {name}: &str =\n    {value:?};\n"));
        } else {
            out.push_str(&line);
            out.push('\n');
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> toml::Table {
        let mut table = toml::Table::new();
        for (_, section, key, _) in CONSTANTS {
            let entry = table
                .entry(section)
                .or_insert_with(|| toml::Value::Table(toml::Table::new()));
            if let toml::Value::Table(inner) = entry {
                inner.insert(key.to_owned(), toml::Value::String(format!("v-{key}")));
            }
        }
        table
    }

    #[test]
    fn renders_every_constant_with_its_doc() {
        let out = render(&sample()).unwrap();
        assert!(out.contains(
            "/// Product name shown to people.\npub const PRODUCT_NAME: &str = \"v-name\";\n"
        ));
        assert_eq!(out.matches("pub const ").count(), CONSTANTS.len());
    }

    #[test]
    fn quotes_and_long_values_stay_valid_rust() {
        let mut table = sample();
        if let Some(toml::Value::Table(product)) = table.get_mut("product") {
            product.insert("tagline".into(), "say \"hi\"".into());
            product.insert("homepage".into(), "h".repeat(120).into());
        }
        let out = render(&table).unwrap();
        assert!(out.contains("TAGLINE: &str = \"say \\\"hi\\\"\";"));
        assert!(out.contains("HOMEPAGE: &str =\n    \"hhhh"));
    }

    #[test]
    fn a_missing_key_is_named() {
        let error = render(&toml::Table::new()).unwrap_err();
        assert!(error.contains("[product] name"), "{error}");
    }
}
