//! Small text helpers shared by the generators.

/// The first line of every generated TypeScript file.
pub fn ts_header(source: &str) -> String {
    format!("// Generated by `cargo xtask gen` from {source}. Do not edit.\n")
}

/// A `SUMMARY.md` for a generated folder, in the documented format.
pub fn summary(folder: &str, entries: &[(&str, &str)]) -> String {
    let mut text = format!("# {folder}\n\n");
    for (name, description) in entries {
        text.push_str(&format!("- `{name}` — {description}\n"));
    }
    text
}

/// `user_cancelled` → `UserCancelled`, the spelling of the protocol's codes.
pub fn pascal_case(snake: &str) -> String {
    snake
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars.next().map_or_else(String::new, |first| {
                first.to_uppercase().chain(chars).collect()
            })
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pascal_case_joins_words() {
        assert_eq!(pascal_case("certificate_not_valid"), "CertificateNotValid");
        assert_eq!(pascal_case("busy"), "Busy");
    }

    #[test]
    fn summary_lists_one_line_per_entry() {
        let text = summary("a/b", &[("x.ts", "the x")]);
        assert_eq!(text, "# a/b\n\n- `x.ts` — the x\n");
    }
}
