//! The generated `index.md` and `SUMMARY.md` of one OS folder.

use std::collections::BTreeMap;

use super::naming::Shot;

/// `SUMMARY.md`: `index.md` plus one row per image.
pub fn render_summary(os: &str, shots: &[Shot]) -> String {
    let mut text = format!("# docs/screenshots/{os}\n\n");
    text.push_str("- `index.md` — every screenshot on one page, light next to dark\n");
    let mut sorted: Vec<&Shot> = shots.iter().collect();
    sorted.sort_by(|a, b| a.file.cmp(&b.file));
    for shot in sorted {
        text.push_str(&format!("- `{}` — {}\n", shot.file, shot.description()));
    }
    text
}

/// `index.md`: a table per window, one row per state.
pub fn render_index(os: &str, shots: &[Shot]) -> String {
    let mut windows: BTreeMap<&str, BTreeMap<&str, [Option<&str>; 2]>> = BTreeMap::new();
    for shot in shots {
        let window = shot.window.as_deref().unwrap_or("other");
        let slot = usize::from(shot.theme.as_deref() == Some("dark"));
        windows
            .entry(window)
            .or_default()
            .entry(&shot.state)
            .or_default()[slot] = Some(&shot.file);
    }
    let mut text =
        format!("# Screenshots: {os}\n\nGenerated by `cargo xtask screenshots`; do not edit.\n");
    for (window, states) in windows {
        text.push_str(&format!(
            "\n## {window}\n\n| State | Light | Dark |\n|---|---|---|\n"
        ));
        for (state, [light, dark]) in states {
            text.push_str(&format!(
                "| {state} | {} | {} |\n",
                image(light),
                image(dark)
            ));
        }
    }
    text
}

fn image(file: Option<&str>) -> String {
    file.map_or_else(String::new, |file| format!("![{file}]({file})"))
}
