// Generated by `cargo xtask gen` from crates/websign-protocol. Do not edit.

/** The protocol version this extension speaks. */
export const PROTOCOL_VERSION = 1;

/** `source` of messages posted by the SDK. */
export const PAGE_SOURCE = "websign-page";

/** `source` of messages posted by the content script. */
export const EXTENSION_SOURCE = "websign-extension";

/** Longest request id the app accepts, in bytes. */
export const MAX_REQUEST_ID_LEN = 64;

/** Longest origin the app accepts, in bytes. */
export const MAX_ORIGIN_LEN = 512;

/** Requests of any kind in flight on one connection. */
export const MAX_IN_FLIGHT_PER_CONNECTION = 16;

/** How long to wait for the `hello` reply of an app that answered before. */
export const APP_RESPONSE_TIMEOUT_MS = 3000;

/** How long an idle native messaging port stays open. */
export const EXTENSION_IDLE_CLOSE_MS = 60_000;
