// Generated by `cargo xtask gen` from i18n/*.toml [site.errors]. Do not edit.

import type { ErrorCode } from "./generated/index.js";

/** A title and a sentence; `{name}` placeholders are left for the caller. */
export interface MessageText {
  readonly title: string;
  readonly body: string;
}

/** The texts of one locale; codes a site never shows have none. */
export type LocaleMessages = Readonly<Partial<Record<ErrorCode, MessageText>>>;

/** Locales with texts, in the order `i18n.md` lists them. */
export type MessageLocale = "en" | "pt-BR" | "pt-PT" | "es" | "fr" | "it" | "de";

/** Title and body per error code, per locale. */
export const MESSAGES: Readonly<Record<MessageLocale, LocaleMessages>> = {
  en: {
    Aborted: {
      title: "Signature stopped",
      body: "The signature was stopped before it finished.",
    },
    AppMissing: {
      title: "Install the WebeSign app",
      body: "The extension needs the app on your computer to sign.",
    },
    AppOutdated: {
      title: "Update the WebeSign app",
      body: "You have version {installed}; {required} or newer is required.",
    },
    Busy: {
      title: "Requests are waiting for confirmation",
      body: "Finish the open requests in the WebeSign window.",
    },
    CertificateNotValid: {
      title: "Certificate out of validity",
      body: "This certificate has expired or isn't valid yet. Choose another one or renew it with your certificate authority.",
    },
    CertificateUnavailable: {
      title: "Certificate unavailable",
      body: "The chosen certificate is no longer available. Plug the token back in or choose another one.",
    },
    DriverFailure: {
      title: "The token driver failed",
      body: "Try again; if it keeps happening, reconnect the token.",
    },
    ExtensionMissing: {
      title: "Install the WebeSign extension",
      body: "To sign in this browser, install the free extension.",
    },
    ExtensionOutdated: {
      title: "Update the WebeSign extension",
      body: "Restart your browser so it updates.",
    },
    InsecureOrigin: {
      title: "Insecure site",
      body: "This site doesn't use https. For your safety, WebeSign won't sign for it.",
    },
    Internal: {
      title: "Something went wrong in WebeSign",
      body: "Open WebeSign diagnostics to report the problem.",
    },
    NoCertificates: {
      title: "No certificates found",
      body: "Plug in your token or insert your card and try again.",
    },
    PinLocked: {
      title: "PIN locked",
      body: "Your token PIN is locked. Unlock it with the PUK and try again.",
    },
    Timeout: {
      title: "The request expired",
      body: "Nobody answered for 5 minutes. Try again.",
    },
    TokenRemoved: {
      title: "The token was removed",
      body: "Plug the token back in and try again.",
    },
    UnsupportedAlgorithm: {
      title: "This certificate can't sign that way",
      body: "Choose another certificate.",
    },
    UserCancelled: {
      title: "Signature cancelled",
      body: "You cancelled the signature.",
    },
  },
  "pt-BR": {
    Aborted: {
      title: "Assinatura interrompida",
      body: "A assinatura foi interrompida antes de terminar.",
    },
    AppMissing: {
      title: "Instale o app WebeSign",
      body: "A extensão precisa do app no computador para assinar.",
    },
    AppOutdated: {
      title: "Atualize o app WebeSign",
      body: "Você tem a versão {installed}; é preciso a {required} ou mais nova.",
    },
    Busy: {
      title: "Há pedidos esperando confirmação",
      body: "Conclua os pedidos abertos na janela do WebeSign.",
    },
    CertificateNotValid: {
      title: "Certificado fora da validade",
      body: "Este certificado venceu ou ainda não começou a valer. Escolha outro ou renove com a sua autoridade certificadora.",
    },
    CertificateUnavailable: {
      title: "Certificado indisponível",
      body: "O certificado escolhido não está mais acessível. Conecte o token de novo ou escolha outro.",
    },
    DriverFailure: {
      title: "O driver do token falhou",
      body: "Tente de novo; se continuar, reconecte o token.",
    },
    ExtensionMissing: {
      title: "Instale a extensão WebeSign",
      body: "Para assinar neste navegador, instale a extensão gratuita.",
    },
    ExtensionOutdated: {
      title: "Atualize a extensão WebeSign",
      body: "Reinicie o navegador para ela se atualizar.",
    },
    InsecureOrigin: {
      title: "Site sem conexão segura",
      body: "Este site não usa https. Por segurança, o WebeSign não assina para ele.",
    },
    Internal: {
      title: "Algo deu errado no WebeSign",
      body: "Abra o diagnóstico do WebeSign para relatar o problema.",
    },
    NoCertificates: {
      title: "Nenhum certificado encontrado",
      body: "Conecte o token ou insira o cartão e tente de novo.",
    },
    PinLocked: {
      title: "PIN bloqueado",
      body: "O PIN do seu token está bloqueado. Desbloqueie com o PUK e tente de novo.",
    },
    Timeout: {
      title: "O pedido expirou",
      body: "Ninguém respondeu em 5 minutos. Tente de novo.",
    },
    TokenRemoved: {
      title: "O token foi removido",
      body: "Conecte o token de novo e tente de novo.",
    },
    UnsupportedAlgorithm: {
      title: "Este certificado não assina desse jeito",
      body: "Escolha outro certificado.",
    },
    UserCancelled: {
      title: "Assinatura cancelada",
      body: "Você cancelou a assinatura.",
    },
  },
  "pt-PT": {
    Aborted: {
      title: "Assinatura interrompida",
      body: "A assinatura foi interrompida antes de terminar.",
    },
    AppMissing: {
      title: "Instale a aplicação WebeSign",
      body: "A extensão precisa da aplicação no computador para assinar.",
    },
    AppOutdated: {
      title: "Atualize a aplicação WebeSign",
      body: "Tem a versão {installed}; é necessária a {required} ou posterior.",
    },
    Busy: {
      title: "Há pedidos a aguardar confirmação",
      body: "Conclua os pedidos abertos na janela do WebeSign.",
    },
    CertificateNotValid: {
      title: "Certificado fora do prazo de validade",
      body: "Este certificado expirou ou ainda não é válido. Escolha outro ou renove-o junto da sua entidade certificadora.",
    },
    CertificateUnavailable: {
      title: "Certificado indisponível",
      body: "O certificado escolhido já não está acessível. Volte a ligar o token ou escolha outro.",
    },
    DriverFailure: {
      title: "O controlador do token falhou",
      body: "Tente novamente; se continuar, volte a ligar o token.",
    },
    ExtensionMissing: {
      title: "Instale a extensão WebeSign",
      body: "Para assinar neste navegador, instale a extensão gratuita.",
    },
    ExtensionOutdated: {
      title: "Atualize a extensão WebeSign",
      body: "Reinicie o navegador para que ela se atualize.",
    },
    InsecureOrigin: {
      title: "Site sem ligação segura",
      body: "Este site não usa https. Por segurança, o WebeSign não assina para ele.",
    },
    Internal: {
      title: "Algo correu mal no WebeSign",
      body: "Abra o diagnóstico do WebeSign para comunicar o problema.",
    },
    NoCertificates: {
      title: "Nenhum certificado encontrado",
      body: "Ligue o token ou introduza o cartão e tente novamente.",
    },
    PinLocked: {
      title: "PIN bloqueado",
      body: "O PIN do seu token está bloqueado. Desbloqueie-o com o PUK e tente novamente.",
    },
    Timeout: {
      title: "O pedido expirou",
      body: "Ninguém respondeu em 5 minutos. Tente novamente.",
    },
    TokenRemoved: {
      title: "O token foi removido",
      body: "Volte a ligar o token e tente novamente.",
    },
    UnsupportedAlgorithm: {
      title: "Este certificado não assina dessa forma",
      body: "Escolha outro certificado.",
    },
    UserCancelled: {
      title: "Assinatura cancelada",
      body: "Cancelou a assinatura.",
    },
  },
  es: {
    Aborted: {
      title: "Firma interrumpida",
      body: "La firma se interrumpió antes de terminar.",
    },
    AppMissing: {
      title: "Instale la app WebeSign",
      body: "La extensión necesita la app en su equipo para firmar.",
    },
    AppOutdated: {
      title: "Actualice la app WebeSign",
      body: "Tiene la versión {installed}; se requiere la {required} o posterior.",
    },
    Busy: {
      title: "Hay solicitudes esperando confirmación",
      body: "Termine las solicitudes abiertas en la ventana de WebeSign.",
    },
    CertificateNotValid: {
      title: "Certificado fuera de validez",
      body: "Este certificado ha caducado o aún no es válido. Elija otro o renuévelo con su autoridad de certificación.",
    },
    CertificateUnavailable: {
      title: "Certificado no disponible",
      body: "El certificado elegido ya no está disponible. Vuelva a conectar el token o elija otro.",
    },
    DriverFailure: {
      title: "Falló el controlador del token",
      body: "Inténtelo de nuevo; si continúa, vuelva a conectar el token.",
    },
    ExtensionMissing: {
      title: "Instale la extensión de WebeSign",
      body: "Para firmar en este navegador, instale la extensión gratuita.",
    },
    ExtensionOutdated: {
      title: "Actualice la extensión de WebeSign",
      body: "Reinicie el navegador para que se actualice.",
    },
    InsecureOrigin: {
      title: "Sitio sin conexión segura",
      body: "Este sitio no usa https. Por su seguridad, WebeSign no firma para él.",
    },
    Internal: {
      title: "Algo salió mal en WebeSign",
      body: "Abra el diagnóstico de WebeSign para informar del problema.",
    },
    NoCertificates: {
      title: "No se encontró ningún certificado",
      body: "Conecte el token o inserte la tarjeta e inténtelo de nuevo.",
    },
    PinLocked: {
      title: "PIN bloqueado",
      body: "El PIN de su token está bloqueado. Desbloquéelo con el PUK e inténtelo de nuevo.",
    },
    Timeout: {
      title: "La solicitud caducó",
      body: "Nadie respondió en 5 minutos. Inténtelo de nuevo.",
    },
    TokenRemoved: {
      title: "Se retiró el token",
      body: "Vuelva a conectar el token e inténtelo de nuevo.",
    },
    UnsupportedAlgorithm: {
      title: "Este certificado no puede firmar así",
      body: "Elija otro certificado.",
    },
    UserCancelled: {
      title: "Firma cancelada",
      body: "Usted canceló la firma.",
    },
  },
  fr: {
    Aborted: {
      title: "Signature interrompue",
      body: "La signature a été interrompue avant la fin.",
    },
    AppMissing: {
      title: "Installez l’application WebeSign",
      body: "L’extension a besoin de l’application sur votre ordinateur pour signer.",
    },
    AppOutdated: {
      title: "Mettez à jour l’application WebeSign",
      body: "Vous avez la version {installed} ; la version {required} ou ultérieure est requise.",
    },
    Busy: {
      title: "Des demandes attendent une confirmation",
      body: "Terminez les demandes ouvertes dans la fenêtre WebeSign.",
    },
    CertificateNotValid: {
      title: "Certificat hors validité",
      body: "Ce certificat a expiré ou n’est pas encore valide. Choisissez-en un autre ou renouvelez-le auprès de votre autorité de certification.",
    },
    CertificateUnavailable: {
      title: "Certificat indisponible",
      body: "Le certificat choisi n’est plus disponible. Rebranchez le jeton ou choisissez-en un autre.",
    },
    DriverFailure: {
      title: "Le pilote du jeton a échoué",
      body: "Réessayez ; si le problème persiste, rebranchez le jeton.",
    },
    ExtensionMissing: {
      title: "Installez l’extension WebeSign",
      body: "Pour signer dans ce navigateur, installez l’extension gratuite.",
    },
    ExtensionOutdated: {
      title: "Mettez à jour l’extension WebeSign",
      body: "Redémarrez votre navigateur pour la mettre à jour.",
    },
    InsecureOrigin: {
      title: "Site non sécurisé",
      body: "Ce site n’utilise pas https. Pour votre sécurité, WebeSign ne signera pas pour lui.",
    },
    Internal: {
      title: "Un problème est survenu dans WebeSign",
      body: "Ouvrez le diagnostic WebeSign pour signaler le problème.",
    },
    NoCertificates: {
      title: "Aucun certificat trouvé",
      body: "Branchez votre jeton ou insérez votre carte à puce, puis réessayez.",
    },
    PinLocked: {
      title: "PIN bloqué",
      body: "Le PIN de votre jeton est bloqué. Déverrouillez-le avec le PUK, puis réessayez.",
    },
    Timeout: {
      title: "La demande a expiré",
      body: "Personne n’a répondu pendant 5 minutes. Réessayez.",
    },
    TokenRemoved: {
      title: "Le jeton a été retiré",
      body: "Rebranchez le jeton et réessayez.",
    },
    UnsupportedAlgorithm: {
      title: "Ce certificat ne peut pas signer ainsi",
      body: "Choisissez un autre certificat.",
    },
    UserCancelled: {
      title: "Signature annulée",
      body: "Vous avez annulé la signature.",
    },
  },
  it: {
    Aborted: {
      title: "Firma interrotta",
      body: "La firma è stata interrotta prima del completamento.",
    },
    AppMissing: {
      title: "Installa l’app WebeSign",
      body: "Per firmare, l’estensione ha bisogno dell’app sul tuo computer.",
    },
    AppOutdated: {
      title: "Aggiorna l’app WebeSign",
      body: "Hai la versione {installed}; è richiesta la {required} o successiva.",
    },
    Busy: {
      title: "Ci sono richieste in attesa di conferma",
      body: "Completa le richieste aperte nella finestra di WebeSign.",
    },
    CertificateNotValid: {
      title: "Certificato non in corso di validità",
      body: "Questo certificato è scaduto o non è ancora valido. Scegline un altro o rinnovalo presso la tua autorità di certificazione.",
    },
    CertificateUnavailable: {
      title: "Certificato non disponibile",
      body: "Il certificato scelto non è più disponibile. Ricollega il token o scegline un altro.",
    },
    DriverFailure: {
      title: "Il driver del token ha avuto un errore",
      body: "Riprova; se il problema persiste, ricollega il token.",
    },
    ExtensionMissing: {
      title: "Installa l’estensione WebeSign",
      body: "Per firmare in questo browser, installa l’estensione gratuita.",
    },
    ExtensionOutdated: {
      title: "Aggiorna l’estensione WebeSign",
      body: "Riavvia il browser per aggiornarla.",
    },
    InsecureOrigin: {
      title: "Sito non sicuro",
      body: "Questo sito non usa https. Per la tua sicurezza, WebeSign non firmerà per esso.",
    },
    Internal: {
      title: "Si è verificato un problema in WebeSign",
      body: "Apri la diagnostica di WebeSign per segnalare il problema.",
    },
    NoCertificates: {
      title: "Nessun certificato trovato",
      body: "Collega il token o inserisci la smart card e riprova.",
    },
    PinLocked: {
      title: "PIN bloccato",
      body: "Il PIN del token è bloccato. Sbloccalo con il PUK e riprova.",
    },
    Timeout: {
      title: "La richiesta è scaduta",
      body: "Nessuno ha risposto per 5 minuti. Riprova.",
    },
    TokenRemoved: {
      title: "Il token è stato rimosso",
      body: "Ricollega il token e riprova.",
    },
    UnsupportedAlgorithm: {
      title: "Questo certificato non può firmare in questo modo",
      body: "Scegli un altro certificato.",
    },
    UserCancelled: {
      title: "Firma annullata",
      body: "Hai annullato la firma.",
    },
  },
  de: {
    Aborted: {
      title: "Signatur abgebrochen",
      body: "Die Signatur wurde vor dem Abschluss abgebrochen.",
    },
    AppMissing: {
      title: "WebeSign-App installieren",
      body: "Zum Signieren benötigt die Erweiterung die App auf Ihrem Computer.",
    },
    AppOutdated: {
      title: "WebeSign-App aktualisieren",
      body: "Sie haben Version {installed}; erforderlich ist {required} oder neuer.",
    },
    Busy: {
      title: "Anfragen warten auf Bestätigung",
      body: "Schließen Sie die offenen Anfragen im WebeSign-Fenster ab.",
    },
    CertificateNotValid: {
      title: "Zertifikat außerhalb der Gültigkeit",
      body: "Dieses Zertifikat ist abgelaufen oder noch nicht gültig. Wählen Sie ein anderes oder erneuern Sie es bei Ihrem Zertifizierungsdiensteanbieter.",
    },
    CertificateUnavailable: {
      title: "Zertifikat nicht verfügbar",
      body: "Das gewählte Zertifikat ist nicht mehr verfügbar. Stecken Sie den Token wieder an oder wählen Sie ein anderes.",
    },
    DriverFailure: {
      title: "Der Token-Treiber ist fehlgeschlagen",
      body: "Versuchen Sie es erneut; wenn das Problem bestehen bleibt, stecken Sie den Token neu an.",
    },
    ExtensionMissing: {
      title: "WebeSign-Erweiterung installieren",
      body: "Um in diesem Browser zu signieren, installieren Sie die kostenlose Erweiterung.",
    },
    ExtensionOutdated: {
      title: "WebeSign-Erweiterung aktualisieren",
      body: "Starten Sie Ihren Browser neu, damit er aktualisiert.",
    },
    InsecureOrigin: {
      title: "Unsichere Website",
      body: "Diese Website verwendet kein https. Zu Ihrer Sicherheit signiert WebeSign nicht für sie.",
    },
    Internal: {
      title: "In WebeSign ist ein Fehler aufgetreten",
      body: "Öffnen Sie die WebeSign-Diagnose, um das Problem zu melden.",
    },
    NoCertificates: {
      title: "Keine Zertifikate gefunden",
      body: "Stecken Sie Ihren Token an oder legen Sie Ihre Chipkarte ein und versuchen Sie es erneut.",
    },
    PinLocked: {
      title: "PIN gesperrt",
      body: "Die PIN Ihres Tokens ist gesperrt. Entsperren Sie sie mit der PUK und versuchen Sie es erneut.",
    },
    Timeout: {
      title: "Die Anfrage ist abgelaufen",
      body: "Innerhalb von 5 Minuten hat niemand geantwortet. Versuchen Sie es erneut.",
    },
    TokenRemoved: {
      title: "Der Token wurde entfernt",
      body: "Stecken Sie den Token wieder an und versuchen Sie es erneut.",
    },
    UnsupportedAlgorithm: {
      title: "Dieses Zertifikat kann so nicht signieren",
      body: "Wählen Sie ein anderes Zertifikat.",
    },
    UserCancelled: {
      title: "Signatur abgebrochen",
      body: "Sie haben die Signatur abgebrochen.",
    },
  },
};
