// Generated by `cargo xtask gen` from project.toml. Do not edit.

/** Chrome Web Store item ID; empty until published. */
export const CHROME_WEB_STORE_ID = "";

/** Edge Add-ons product ID; empty until published. */
export const EDGE_ADDONS_ID = "";

/** addons.mozilla.org listing slug; empty until published. */
export const FIREFOX_AMO_SLUG = "";

/** The project's site; its download page lists every way to install. */
export const HOMEPAGE = "https://diagnos-tech.github.io/signlocal/";
