//! `cargo xtask gen`.
//!
//! 1. `cargo test -p websign-protocol --features typescript export_bindings`
//!    with `TS_RS_EXPORT_DIR` → `sdk/src/generated/`, then copies to
//!    `extension/src/generated/` and `clients/node/src/generated/`;
//! 2. `i18n/*.toml` `[popup]`, `[store]`, `[extension]` →
//!    `extension/public/_locales/<xx_YY>/messages.json`;
//! 3. `i18n/*.toml` `[site.errors]` → `sdk/src/messages.gen.ts`;
//! 4. `project.toml` → `extension/src/generated/project.ts` and
//!    `clients/node/src/generated/project.ts` (IDs, MIN_APP_VERSION).
//!
//! Every generated file starts with a "generated by cargo xtask gen" header.

/// `cargo xtask gen`.
#[derive(Debug, clap::Args)]
pub struct GenArgs {
    /// Only this generator: `ts`, `locales`, `messages`, `project`.
    #[arg(long)]
    pub only: Option<String>,
}

/// Runs the generators.
pub fn run(args: &GenArgs) -> Result<(), String> {
    let _ = args;
    todo!("testing.md §Generated files")
}
