#Requires -Version 7.2
<#
.SYNOPSIS
    Creates (or removes) software test certificates that exercise every
    Windows signing path of websign-probe.

.DESCRIPTION
    All certificates go to Cert:\CurrentUser\My with a subject that starts
    with "CN=websign-probe test", so -Remove deletes exactly these (with their
    private keys) and nothing else.

      cng-rsa2048        RSA-2048 in the Microsoft Software KSP (CNG)
      cng-p256/-p384     ECDSA in the Microsoft Software KSP (CNG)
      capi-aes-rsa2048   RSA-2048 in the Enhanced RSA and AES CSP (CAPI, PROV_RSA_AES)
      a1-rsa2048         an "A1": AT_KEYEXCHANGE key in the Enhanced CSP v1.0
                         (CAPI, PROV_RSA_FULL, AT_KEYEXCHANGE), as the import
                         wizard does with certificates bought as a file
      capi-base-rsa2048  RSA-2048 in the Base CSP v1.0 (PROV_RSA_FULL), when
                         the cmdlet accepts that provider

    Writes one object per certificate: Name, Thumbprint, Sha256 (the probe's
    fingerprint), Api (CNG or CAPI), Provider, Key (RSA or EC) and AllowApi
    (the native call expected with --ncrypt allow).

    Every key is created in a child process with a time limit
    (-StepTimeoutSeconds): a provider that waits for a dialog nobody can see
    fails its step, named in the log, instead of hanging the CI job.

.EXAMPLE
    $certs = ./make-test-certs.ps1
    ./make-test-certs.ps1 -Remove
#>
[CmdletBinding()]
param(
    # Delete the test certificates and their keys instead of creating them.
    [switch] $Remove,
    # Time limit for creating (or importing) one certificate.
    [int] $StepTimeoutSeconds = 120
)

$ErrorActionPreference = 'Stop'
# certutil's exit code is checked by hand.
$PSNativeCommandUseErrorActionPreference = $false
Set-StrictMode -Version Latest
. "$PSScriptRoot/invoke-bounded.ps1"

$SubjectPrefix = 'CN=websign-probe test'
$Store = 'Cert:\CurrentUser\My'
$Ksp = 'Microsoft Software Key Storage Provider'
$AesCsp = 'Microsoft Enhanced RSA and AES Cryptographic Provider'
$EnhancedCsp = 'Microsoft Enhanced Cryptographic Provider v1.0'
$BaseCsp = 'Microsoft Base Cryptographic Provider v1.0'

function Remove-TestCertificate {
    Get-ChildItem -Path $Store |
        Where-Object { $_.Subject -like "$SubjectPrefix*" } |
        ForEach-Object {
            Write-Host "Removing $($_.Subject) ($($_.Thumbprint))"
            Remove-Item -LiteralPath $_.PSPath -DeleteKey
        }
}

# New-SelfSignedCertificate runs in a child PowerShell with a time limit: the
# key is generated by the provider named in $KeyParameters, and a provider
# that waits for UI would otherwise block this script for good.
function New-TestCertificate([string] $Name, [hashtable] $KeyParameters) {
    $parameters = @{
        Subject           = "$SubjectPrefix $Name"
        CertStoreLocation = $Store
        Type              = 'Custom'
        KeyUsage          = 'DigitalSignature', 'NonRepudiation'
        KeyExportPolicy   = 'NonExportable'
        HashAlgorithm     = 'SHA256'
    }
    foreach ($key in $KeyParameters.Keys) { $parameters[$key] = $KeyParameters[$key] }
    $json = ($parameters | ConvertTo-Json -Compress).Replace("'", "''")
    $script = "`$parameters = '$json' | ConvertFrom-Json -AsHashtable; " +
        "`$parameters.NotAfter = (Get-Date).AddDays(7); " +
        "(New-SelfSignedCertificate @parameters).Thumbprint"
    $run = Invoke-BoundedPowerShell -Script $script -TimeoutSeconds $StepTimeoutSeconds `
        -Label "New-SelfSignedCertificate $Name ($($parameters['Provider']))"
    if ($run.TimedOut) {
        throw "TIMEOUT in New-SelfSignedCertificate $Name after $StepTimeoutSeconds s"
    }
    $thumbprint = @($run.Stdout | Where-Object { $_ -match '^[0-9A-F]{40}$' }) | Select-Object -Last 1
    if ($run.ExitCode -ne 0 -or -not $thumbprint) {
        throw "New-SelfSignedCertificate $Name failed (exit code $($run.ExitCode)):`n$($run.Lines -join "`n")"
    }
    Get-Item -LiteralPath "$Store\$thumbprint"
}

# The way certificate files usually end up in Windows: a PFX imported into
# the default legacy CSP, which is PROV_RSA_FULL and predates SHA-2.
function ConvertTo-Result($Certificate, [string] $Name, [string] $Api, [string] $Provider,
    [string] $Key, [string] $AllowApi) {
    [pscustomobject]@{
        Name       = $Name
        Thumbprint = $Certificate.Thumbprint
        Sha256     = [Convert]::ToHexString(
            [Security.Cryptography.SHA256]::HashData($Certificate.RawData)).ToLowerInvariant()
        Api        = $Api
        Provider   = $Provider
        Key        = $Key
        AllowApi   = $AllowApi
    }
}

if ($Remove) {
    Remove-TestCertificate
    return
}

$cng = @{ Provider = $Ksp }
$rsa = @{ KeyAlgorithm = 'RSA'; KeyLength = 2048 }

ConvertTo-Result (New-TestCertificate 'cng-rsa2048' ($cng + $rsa)) `
    'cng-rsa2048' 'CNG' $Ksp 'RSA' 'NCryptSignHash'
ConvertTo-Result (New-TestCertificate 'cng-p256' ($cng + @{ KeyAlgorithm = 'ECDSA_nistP256'; CurveExport = 'CurveName' })) `
    'cng-p256' 'CNG' $Ksp 'EC' 'NCryptSignHash'
ConvertTo-Result (New-TestCertificate 'cng-p384' ($cng + @{ KeyAlgorithm = 'ECDSA_nistP384'; CurveExport = 'CurveName' })) `
    'cng-p384' 'CNG' $Ksp 'EC' 'NCryptSignHash'
ConvertTo-Result (New-TestCertificate 'capi-aes-rsa2048' ($rsa + @{ Provider = $AesCsp; KeySpec = 'Signature' })) `
    'capi-aes-rsa2048' 'CAPI' $AesCsp 'RSA' 'CryptSignHash'

# An "A1": what importing a .pfx leaves behind is an AT_KEYEXCHANGE key in the
# Enhanced CSP v1.0 (PROV_RSA_FULL). The key is created there directly:
# `certutil -importpfx` waits on an invisible prompt on Windows Server 2025
# runners. Like the Base CSP, this provider self-signs with SHA-1 only.
try {
    $a1 = New-TestCertificate 'a1-rsa2048' ($rsa + @{
            Provider = $EnhancedCsp; KeySpec = 'KeyExchange'; HashAlgorithm = 'SHA1'
        })
    ConvertTo-Result $a1 'a1-rsa2048' 'CAPI' $EnhancedCsp 'RSA' 'CryptSignHash (PROV_RSA_AES)'
} catch {
    Write-Warning "Skipping a1-rsa2048 (optional): the Enhanced CSP key could not be made: $_"
}

# The Base CSP cannot hash with SHA-2, so its own certificate is self-signed
# with SHA-1; only the key matters here.
try {
    $base = New-TestCertificate 'capi-base-rsa2048' ($rsa + @{
            Provider = $BaseCsp; KeySpec = 'Signature'; HashAlgorithm = 'SHA1'
        })
    ConvertTo-Result $base 'capi-base-rsa2048' 'CAPI' $BaseCsp 'RSA' 'CryptSignHash (PROV_RSA_AES)'
} catch {
    Write-Warning "Skipping capi-base-rsa2048 (optional): the Base CSP key could not be made: $_"
}
